import type { Metadata } from 'next'
import './globals.css'
import SideNav from './sidenav/page'
import { Inter } from 'next/font/google';

export const metadata: Metadata = {
    title: 'Portfolio',
    description: 'Generated by create next app',
}
export const inter = Inter({ subsets: ['latin'] });

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="fr">
            <body className={`${inter.className} antialiased flex h-screen flex-col md:flex-row md:overflow-hidden`}>
                <div className="w-full flex-none md:w-64">
                    <SideNav />
                </div>
                <div className="flex-grow p-6 md:overflow-y-auto md:p-12">{children}</div>
            </body>
        </html>
    )
}
