import type { Metadata } from 'next'
import './globals.css'
import SideNav from './sidenav/page'
import Head from 'next/head'

export const metadata: Metadata = {
  title: 'Portfolio',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
     <html lang="fr">
      <Head>
        <title>Dashboard - Thimothée Lepetz</title>
      </Head>
      <body className="flex h-screen flex-col md:flex-row md:overflow-hidden">
        <div className="w-full flex-none md:w-64">
          <SideNav />
        </div>
        <div className="flex-grow p-6 md:overflow-y-auto md:p-12">{children}</div>
      </body>
    </html>
  )
}
